-- Better Auth-owned tables (user, session, account, verification, twoFactor).
-- Generated by Better Auth's own migration compiler (better-auth 1.6.25, see
-- apps/server/scripts/gen-better-auth-sql.ts) — spec 1: auth tables are managed
-- by Better Auth and touched only through Better Auth APIs.
-- The final ALTER adds the app-side FK from employees.user_id (spec 1).

create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null, "twoFactorEnabled" boolean, "role" text, "banned" boolean, "banReason" text, "banExpires" timestamptz);--> statement-breakpoint

create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade, "impersonatedBy" text);--> statement-breakpoint

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);--> statement-breakpoint

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);--> statement-breakpoint

create table "twoFactor" ("id" text not null primary key, "secret" text not null, "backupCodes" text not null, "userId" text not null references "user" ("id") on delete cascade, "verified" boolean, "failedVerificationCount" integer, "lockedUntil" timestamptz);--> statement-breakpoint

create index "session_userId_idx" on "session" ("userId");--> statement-breakpoint

create index "account_userId_idx" on "account" ("userId");--> statement-breakpoint

create index "verification_identifier_idx" on "verification" ("identifier");--> statement-breakpoint

create index "twoFactor_secret_idx" on "twoFactor" ("secret");--> statement-breakpoint

create index "twoFactor_userId_idx" on "twoFactor" ("userId");--> statement-breakpoint

ALTER TABLE "employees" ADD CONSTRAINT "employees_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;
